<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  
  <title>java 线程的运行时异常处理-UncaughtExceptionHandler | 十只橘猫九只胖</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <meta name="description" content="首先，有个问题，如果Java子线程发生异常会怎么样？实际上会导致该线程直接终止。当年自己写了个线程模型大概是这样的：
123Spring容器启动 (1)  -&amp;gt; 主线程中启动一个子线程T，在while循环中去接收socket请求 (2)    -&amp;gt; 收到一个请求，submit一个线程 (3)
当时我一只担心步骤2的线程T会因为什么而挂掉，然后大家没办法上传文件。而当时完全不知道Unca">
<meta property="og:type" content="article">
<meta property="og:title" content="java 线程的运行时异常处理-UncaughtExceptionHandler">
<meta property="og:url" content="http://hybnew.github.io/2017/03/01/java-线程的运行时异常处理-UncaughtExceptionHandler/index.html">
<meta property="og:site_name" content="十只橘猫九只胖">
<meta property="og:description" content="首先，有个问题，如果Java子线程发生异常会怎么样？实际上会导致该线程直接终止。当年自己写了个线程模型大概是这样的：
123Spring容器启动 (1)  -&amp;gt; 主线程中启动一个子线程T，在while循环中去接收socket请求 (2)    -&amp;gt; 收到一个请求，submit一个线程 (3)
当时我一只担心步骤2的线程T会因为什么而挂掉，然后大家没办法上传文件。而当时完全不知道Unca">
<meta property="og:updated_time" content="2017-03-01T06:40:21.066Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="java 线程的运行时异常处理-UncaughtExceptionHandler">
<meta name="twitter:description" content="首先，有个问题，如果Java子线程发生异常会怎么样？实际上会导致该线程直接终止。当年自己写了个线程模型大概是这样的：
123Spring容器启动 (1)  -&amp;gt; 主线程中启动一个子线程T，在while循环中去接收socket请求 (2)    -&amp;gt; 收到一个请求，submit一个线程 (3)
当时我一只担心步骤2的线程T会因为什么而挂掉，然后大家没办法上传文件。而当时完全不知道Unca">
  
    <link rel="alternate" href="/atom.xml" title="十只橘猫九只胖" type="application/atom+xml">
  
  
    <link rel="icon" href="/favicon.png">
  
  
    <link href="//fonts.googleapis.com/css?family=Source+Code+Pro" rel="stylesheet" type="text/css">
  
  <link rel="stylesheet" href="/css/style.css">
  

</head>

<body>
  <div id="container">
    <div id="wrap">
      <header id="header">
  <div id="banner"></div>
  <div id="header-outer" class="outer">
    <div id="header-title" class="inner">
      <h1 id="logo-wrap">
        <a href="/" id="logo">十只橘猫九只胖</a>
      </h1>
      
        <h2 id="subtitle-wrap">
          <a href="/" id="subtitle">还有一只特别胖</a>
        </h2>
      
    </div>
    <div id="header-inner" class="inner">
      <nav id="main-nav">
        <a id="main-nav-toggle" class="nav-icon"></a>
        
          <a class="main-nav-link" href="/">Home</a>
        
          <a class="main-nav-link" href="/archives">Archives</a>
        
      </nav>
      <nav id="sub-nav">
        
          <a id="nav-rss-link" class="nav-icon" href="/atom.xml" title="RSS Feed"></a>
        
        <a id="nav-search-btn" class="nav-icon" title="搜索"></a>
      </nav>
      <div id="search-form-wrap">
        <form action="//google.com/search" method="get" accept-charset="UTF-8" class="search-form"><input type="search" name="q" results="0" class="search-form-input" placeholder="Search"><button type="submit" class="search-form-submit">&#xF002;</button><input type="hidden" name="sitesearch" value="http://hybnew.github.io"></form>
      </div>
    </div>
  </div>
</header>
      <div class="outer">
        <section id="main"><article id="post-java-线程的运行时异常处理-UncaughtExceptionHandler" class="article article-type-post" itemscope itemprop="blogPost">
  <div class="article-meta">
    <a href="/2017/03/01/java-线程的运行时异常处理-UncaughtExceptionHandler/" class="article-date">
  <time datetime="2017-03-01T05:41:33.000Z" itemprop="datePublished">2017-03-01</time>
</a>
    
  </div>
  <div class="article-inner">
    
    
      <header class="article-header">
        
  
    <h1 class="article-title" itemprop="name">
      java 线程的运行时异常处理-UncaughtExceptionHandler
    </h1>
  

      </header>
    
    <div class="article-entry" itemprop="articleBody">
      
        <p>首先，有个问题，如果Java子线程发生异常会怎么样？实际上会导致该线程直接终止。<br>当年自己写了个线程模型大概是这样的：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">Spring容器启动 (1)</div><div class="line">  -&gt; 主线程中启动一个子线程T，在while循环中去接收socket请求 (2)</div><div class="line">    -&gt; 收到一个请求，submit一个线程 (3)</div></pre></td></tr></table></figure>
<p>当时我一只担心步骤2的线程T会因为什么而挂掉，然后大家没办法上传文件。而当时完全不知道UncaughtExceptionHandler的存在，多希望有一丁点指导啊。<br>那么如何处理可能出现的异常而不至于线程直接挂掉呢？</p>
<p>第一，把整个run中的异常在内部捕获掉<br>第二，直接在线程中setUncaughtExceptionHandler,将异常处理与run分开。</p>
<p>其实，有的同学可以疑惑，为什么不能直接把整个线程用try-catch包裹起来。因为这本来就没有什么用，譬如：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line">// 普通线程即使使用try...catch也无法捕获到抛出的异常</div><div class="line">       try &#123;</div><div class="line">           Thread t = new Thread();</div><div class="line">           t.start();</div><div class="line">       &#125; catch (Exception e) &#123;</div><div class="line">           System.out.println(&quot;catch RunTimeException &quot;); // 不起作用</div><div class="line">       &#125;</div></pre></td></tr></table></figure>
<p>假设t是从线程x中 <code>new</code> 出来的，那么x称为t的父线程。而线程与线程间的运行本是异步的（当然如果不使用线程间通信机制的情况下），有可能x在t还没结束时先结束，这是有可能的，如果x不是主线程的话。<br>所以，try-catch在异步的线程中捕获是没有意义的。<br>正确的方法是：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div></pre></td><td class="code"><pre><div class="line">new Thread(new Runnable() &#123;</div><div class="line">    @Override</div><div class="line">    public void run() &#123;</div><div class="line">        try&#123;//wrap all code</div><div class="line">            Integer.parseInt(&quot;sfasf&quot;);</div><div class="line">            System.out.println(0);</div><div class="line">        &#125;catch(...)&#123;&#125;</div><div class="line">    &#125;</div><div class="line">&#125;).start();</div></pre></td></tr></table></figure></p>
<p>或者使用UncaughtExceptionHandler 捕获线程运行体的运行时异常，使用也很简单：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div></pre></td><td class="code"><pre><div class="line"></div><div class="line">/**</div><div class="line"> * 继承UncaughtExceptionHandler 接口</div><div class="line"> */</div><div class="line">class ErrHandler implements UncaughtExceptionHandler</div><div class="line">&#123;</div><div class="line">    public void uncaughtException(Thread t, Throwable e)</div><div class="line">    &#123;</div><div class="line">        System.out.println(&quot;This is:&quot; + t.getName() + &quot;,Message:&quot; + e.getMessage());</div><div class="line">        e.printStackTrace();</div><div class="line">    &#125;</div><div class="line">&#125;</div></pre></td></tr></table></figure></p>
<p>在线程中使用：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div></pre></td><td class="code"><pre><div class="line">new Thread(new Runnable() &#123;</div><div class="line">    @Override</div><div class="line">    public void run() &#123;</div><div class="line"></div><div class="line">        Thread.currentThread().setUncaughtExceptionHandler(ErrHandler);</div><div class="line">        //Thread.currentThread().setUncaughtExceptionHandler((t, e) -&gt; &#123;</div><div class="line">        //    System.out.println(&quot;current thread is &quot; + t.getName() + &quot; &quot; + e.getMessage());</div><div class="line">        //&#125;);</div><div class="line">        Integer.parseInt(&quot;sfasf&quot;);</div><div class="line">        System.out.println(0);</div><div class="line">    &#125;</div><div class="line">&#125;).start();</div></pre></td></tr></table></figure></p>
<p>如果没有捕获异常，不会输出0，而有了handler则不影响下面的执行，会正常输出了。<br>或者是：<br><figure class="highlight plain"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">Thread a = new Thread();</div><div class="line">a.setUncaughtExceptionHandler(ErrHandler);</div></pre></td></tr></table></figure></p>
<p>正如上面所写，在java 8中还可以用lamda表达式简化语法，用匿名handler代替。不过使用<code>a.setUEH(handler)</code>这种方式是策略模式的体现，更容易在需要的时候随时替换handler的实现，正如sort函数的Comparator参数一样。</p>

      
    </div>
    <footer class="article-footer">
      <a data-url="http://hybnew.github.io/2017/03/01/java-线程的运行时异常处理-UncaughtExceptionHandler/" data-id="cizqlezly0004vsgsqtwmdaiu" class="article-share-link">Share</a>
      
      
    </footer>
  </div>
  
    
<nav id="article-nav">
  
    <a href="/2017/03/01/本博客的入坑纪实-Hexo博客平台/" id="article-nav-newer" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Newer</strong>
      <div class="article-nav-title">
        
          本博客的入坑纪实-Hexo博客平台
        
      </div>
    </a>
  
  
    <a href="/2017/03/01/HashMap-源码分析/" id="article-nav-older" class="article-nav-link-wrap">
      <strong class="article-nav-caption">Older</strong>
      <div class="article-nav-title">HashMap 源码分析</div>
    </a>
  
</nav>

  
</article>

</section>
        
          <aside id="sidebar">
  
    

  
    

  
    
  
    
  <div class="widget-wrap">
    <h3 class="widget-title">归档</h3>
    <div class="widget">
      <ul class="archive-list"><li class="archive-list-item"><a class="archive-list-link" href="/archives/2017/03/">三月 2017</a></li></ul>
    </div>
  </div>


  
    
  <div class="widget-wrap">
    <h3 class="widget-title">最新文章</h3>
    <div class="widget">
      <ul>
        
          <li>
            <a href="/2017/03/01/本博客的入坑纪实-Hexo博客平台/">本博客的入坑纪实-Hexo博客平台</a>
          </li>
        
          <li>
            <a href="/2017/03/01/java-线程的运行时异常处理-UncaughtExceptionHandler/">java 线程的运行时异常处理-UncaughtExceptionHandler</a>
          </li>
        
          <li>
            <a href="/2017/03/01/HashMap-源码分析/">HashMap 源码分析</a>
          </li>
        
          <li>
            <a href="/2017/03/01/CocurrentHashMap-源码试解读/">CocurrentHashMap 源码试解读</a>
          </li>
        
          <li>
            <a href="/2017/03/01/AbstractQueuedSynchronizer-AQS-源码试解读/">AbstractQueuedSynchronizer (AQS) 源码试解读</a>
          </li>
        
      </ul>
    </div>
  </div>

  
</aside>
        
      </div>
      <footer id="footer">
  
  <div class="outer">
    <div id="footer-info" class="inner">
      &copy; 2017 Rick Ho<br>
      Powered by <a href="http://hexo.io/" target="_blank">Hexo</a>
    </div>
  </div>
</footer>
    </div>
    <nav id="mobile-nav">
  
    <a href="/" class="mobile-nav-link">Home</a>
  
    <a href="/archives" class="mobile-nav-link">Archives</a>
  
</nav>
    

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>


  <link rel="stylesheet" href="/fancybox/jquery.fancybox.css">
  <script src="/fancybox/jquery.fancybox.pack.js"></script>


<script src="/js/script.js"></script>

  </div>
</body>
</html>